In [1]:
import pandas as pd
import numpy as np


In [2]:

s = pd.read_csv("https://raw.githubusercontent.com/AP-Skill-Development-Corporation/DataScienceUsingPython-Internship-SRM-University/main/Datasets/Datasets-master/Regression/age_salary_hours.csv")
s.head()

Age  Annual Salary  Weekly hours                    Education
0   72       160000.0          40.0  Bachelor's degree or higher
1   72       100000.0          50.0  Bachelor's degree or higher
2   31       120000.0          40.0  Bachelor's degree or higher
3   28        45000.0          40.0  Bachelor's degree or higher
4   54        85000.0          40.0  Bachelor's degree or higher

In [3]:
s.shape

(500, 4)

In [4]:
s.isnull().sum()

Age              0
Annual Salary    0
Weekly hours     0
Education        0
dtype: int64

In [5]:
x = s[["Age"]]
x.head()

Age
0   72
1   72
2   31
3   28
4   54

In [6]:
y = s["Weekly hours"]
y.head()

0    40.0
1    50.0
2    40.0
3    40.0
4    40.0
Name: Weekly hours, dtype: float64

In [7]:
from sklearn.linear_model import LinearRegression
l_model = LinearRegression()
l_model.fit(x, y)

LinearRegression()

In [8]:
predicted = l_model.predict(x)
predicted

array([18.06802824, 18.06802824, 37.51243005, 38.93519116, 26.60459489,
       30.87287821, 12.37698381, 18.54228194, 19.96504305, 30.39862451,
       24.23332638, 16.64526713, 27.07884859, 27.07884859, 41.30645967,
       42.72922078, 22.81056527, 11.90273011, 33.24414673, 29.92437081,
       34.66690783, 34.66690783, 36.08966894, 36.08966894, 30.39862451,
       40.35795227, 42.25496708, 33.24414673, 31.34713192, 34.19265413,
       21.38780416, 31.82138562, 21.38780416, 35.61541524, 10.0057153 ,
       25.65608748, 26.60459489, 28.9758634 , 17.11952084, 19.01653565,
       35.61541524, 37.51243005, 26.13034119, 26.60459489, 17.59377454,
       14.27399862, 41.30645967, 30.87287821, 30.87287821, 33.24414673,
       10.9542227 , 10.0057153 , 24.23332638, 33.24414673, 22.81056527,
       24.23332638, 20.43929676,  7.16019308, 36.08966894, 34.19265413,
       30.87287821, 33.24414673, 18.06802824, 18.06802824, 26.60459489,
       26.60459489, 33.71840043, 42.72922078, 37.98668375, 38.46

In [9]:
x.loc[100]


Age    55
Name: 100, dtype: int64

In [10]:
y.loc[100]

50.0

In [11]:
l_model.predict([[55]])

array([26.13034119])

In [12]:
from sklearn.metrics import r2_score
r2_score(y, predicted) * 100

17.641761291331616

In [13]:
y.min()

0.0

In [14]:
y.max()

99.0

In [15]:
y = l_model.coef_*x.loc[100] + l_model.intercept_
y

Age    26.130341
Name: 100, dtype: float64

In [16]:
x.loc[100]

Age    55
Name: 100, dtype: int64

In [17]:
l_model.predict([[55]])

array([26.13034119])

In [18]:
s = pd.read_csv("https://raw.githubusercontent.com/AP-Skill-Development-Corporation/DataScienceUsingPython-Internship-SRM-University/main/Datasets/Datasets-master/Regression/age_salary_hours.csv")
s.head()

Age  Annual Salary  Weekly hours                    Education
0   72       160000.0          40.0  Bachelor's degree or higher
1   72       100000.0          50.0  Bachelor's degree or higher
2   31       120000.0          40.0  Bachelor's degree or higher
3   28        45000.0          40.0  Bachelor's degree or higher
4   54        85000.0          40.0  Bachelor's degree or higher

In [19]:
x = s[["Age","Annual Salary"]]
x

Age  Annual Salary
0     72       160000.0
1     72       100000.0
2     31       120000.0
3     28        45000.0
4     54        85000.0
..   ...            ...
495   27        47000.0
496   53       132000.0
497   51        10100.0
498   32        57000.0
499   18        18700.0

[500 rows x 2 columns]

In [20]:

y = s["Weekly hours"]
y

0      40.0
1      50.0
2      40.0
3      40.0
4      40.0
       ... 
495    40.0
496    70.0
497    20.0
498    35.0
499    20.0
Name: Weekly hours, Length: 500, dtype: float64

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 30)

In [22]:
l_model = LinearRegression()
l_model.fit(x_train, y_train)

LinearRegression()

In [23]:
predicted = l_model.predict(x_test)
predicted

array([34.43248909, 38.59576928, 37.2500884 ,  6.81783619, 34.54626967,
       31.19151029, 33.86358618, 41.73569132, 38.74102586, 21.6203258 ,
       34.18935669, 23.3449195 , 16.2376023 , 29.1566506 , 50.81378215,
       36.54282449, 14.89192143, 37.22484089, 36.8713757 , 17.13472288,
       37.31993599, 37.00708943, 38.04621893, 39.76471756, 12.64911997,
       14.44336114,  9.95775822, 38.66561687, 23.86312725, 39.42039498,
       11.75199939, 40.61723806, 42.18425161, 44.18047288, 82.97532226,
       26.9332017 , 29.80129604,  9.50919793, 16.2376023 , 33.80686266,
       41.29302597, 10.40631852, 16.68616259, 39.10761512, 38.36197962,
       37.00384176, 36.63758605, 28.94877554, 28.34873017, 38.83300672,
       31.34306208, 28.35462512, 35.97425512, 11.75199939, 16.2376023 ,
       26.55543662, 13.14817529, 36.62479552, 26.16894743, 36.83956615,
       36.28378732, 25.10125604, 33.73145366, 30.48397953, 31.77916538,
       18.48040376, 25.41701673, 10.85487881, 27.00304929, 28.10

In [24]:
r2_score(y_test, predicted) * 100

34.6552358292705

In [25]:
l  = list(x_train.iloc[20])
l

[60.0, 0.0]

In [26]:

y_train.loc[20]

40.0

In [27]:

l_model.predict([l])

array([19.37752434])