In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])
print(a,a.dtype)

[1 2 3 4 5 6] int32


In [4]:

a = np.array([1,2,3,4,5,6], dtype='bool_')
print(a,a.dtype)

[ True  True  True  True  True  True] bool


In [5]:
a = np.array([1,2,3,4,5,6], dtype='uint32')
print(a,a.dtype)

[1 2 3 4 5 6] uint32


In [6]:
a = np.array([1,2,3,4,5,6], dtype='float32')
print(a,a.dtype)

[1. 2. 3. 4. 5. 6.] float32


In [7]:
a = np.array([1,2,3,4,5,6], dtype='complex_')
print(a,a.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j] complex128


In [8]:
a = np.timedelta64(1,'D')
print(a,a.dtype)

1 days timedelta64[D]


In [9]:
a = np.array(['2002-05-15','2009-07-16','2004-03-20'], dtype='datetime64')
a

array(['2002-05-15', '2009-07-16', '2004-03-20'], dtype='datetime64[D]')

In [10]:
a = np.array([1,2,3,4,5,6], dtype='O')
print(a,a.dtype)

[1 2 3 4 5 6] object


In [11]:
a = np.array(['H','Hi','Howdy'])
print(a,a.dtype)

['H' 'Hi' 'Howdy'] <U5


In [12]:
a = np.array([u'\265E', u'\265F'], dtype='U')
a

array(['µE', 'µF'], dtype='<U2')

TypeError: void() takes at most 1 argument (2 given)